export const DATA_SOURCE = 'DATA_SOURCE';

export const USER_REPOSITORY = 'USER_REPOSITORY';
export const POST_REPOSITORY = 'POST_REPOSITORY';
export const TEAM_REPOSITORY = 'TEAM_REPOSITORY';
export const AUTH_TOKEN_REPOSITORY = 'AUTH_TOKEN_REPOSITORY';
export const USER_PROFILE_REPOSITORY = 'USER_PROFILE_REPOSITORY';
export const SOCIAL_ACCOUNT_REPOSITORY = 'SOCIAL_ACCOUNT_REPOSITORY';

export const ACCESS_TOKEN_SECRET = 'ACCESS_TOKEN_SECRET';
export const REFRESH_TOKEN_SECRET = 'REFRESH_TOKEN_SECRET';
export const REGISTER_TOKEN_SECRET = 'REGISTER_TOKEN_SECRET';
export const ACCESS_TOKEN_EXPIRATION_TIME = 'ACCESS_TOKEN_EXPIRATION_TIME';
export const REFRESH_TOKEN_EXPIRATION_TIME = 'REFRESH_TOKEN_EXPIRATION_TIME';
export const REGISTER_TOKEN_EXPIRATION_TIME = 'REGISTER_TOKEN_EXPIRATION_TIME';

export const GROUP_POST = 'GROUP_DETAIL_POST';
export const GROUP_ALL_POSTS = 'GROUP_ALL_POSTS';
